//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Departent = new HashSet<Departent>();
        }
    
        public string CmopanyCode { get; set; }
        public string CompanyAbbr { get; set; }
        public string CompanyFullName { get; set; }
        public string Corporate { get; set; }
        public Nullable<System.DateTime> FoundDT { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public string IsCenter { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departent> Departent { get; set; }
    }
}
