//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContainer : DbContext
    {
        public DBContainer()
            : base("name=DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TransferBill> TransferBill { get; set; }
        public virtual DbSet<BackInput> BackInput { get; set; }
        public virtual DbSet<OtherInput> OtherInput { get; set; }
        public virtual DbSet<DIYBill> DIYBill { get; set; }
        public virtual DbSet<LocationChange> LocationChange { get; set; }
        public virtual DbSet<CheckBill> CheckBill { get; set; }
        public virtual DbSet<GiveBill> GiveBill { get; set; }
        public virtual DbSet<BackOutput> BackOutput { get; set; }
        public virtual DbSet<OtherOutput> OtherOutput { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<InWarehouse> InWarehouse { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<TaskBill> TaskBill { get; set; }
        public virtual DbSet<GoodItem> GoodItem { get; set; }
        public virtual DbSet<CheckDetail> CheckDetail { get; set; }
        public virtual DbSet<InOutType> InOutType { get; set; }
        public virtual DbSet<BusinessType> BusinessType { get; set; }
        public virtual DbSet<LineWay> LineWay { get; set; }
        public virtual DbSet<LoadGoodsType> LoadGoodsType { get; set; }
        public virtual DbSet<ItemLine> ItemLine { get; set; }
        public virtual DbSet<ItemUnit> ItemUnit { get; set; }
        public virtual DbSet<CostItem> CostItem { get; set; }
        public virtual DbSet<ReceiveFile> ReceiveFile { get; set; }
        public virtual DbSet<SendFile> SendFileSet { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Departent> Departent { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRelation> UserRelation { get; set; }
        public virtual DbSet<UserFramework> UserFramework { get; set; }
        public virtual DbSet<CostUnitList> CostUnitList { get; set; }
        public virtual DbSet<LoadingExpensesBill> LoadingExpensesBill { get; set; }
        public virtual DbSet<LaborCostBill> LaborCostBill { get; set; }
        public virtual DbSet<OtherExpenseList> OtherExpenseList { get; set; }
        public virtual DbSet<CostUnitListDetail> CostUnitListDetail { get; set; }
        public virtual DbSet<OtherExpenseListDetail> OtherExpenseListDetail { get; set; }
        public virtual DbSet<LineWayAndDealer> LineWayAndDealer { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleMenuRelation> RoleMenuRelation { get; set; }
        public virtual DbSet<UserRoleRelation> UserRoleRelation { get; set; }
        public virtual DbSet<LoadingAndLaborCostDetail> LoadingAndLaborCostDetail { get; set; }
        public virtual DbSet<ErrorRecort> ErrorRecort { get; set; }
    }
}
