//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departent
    {
        public string DeptCode { get; set; }
        public Nullable<int> DeptType { get; set; }
        public string CompanyCode { get; set; }
        public string DeptName { get; set; }
        public string TEL { get; set; }
        public Nullable<int> ContractType { get; set; }
        public string IsCenter { get; set; }
        public string Address { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> ProvinceCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<int> AreaCode { get; set; }
    }
}
