//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineWayAndDealer
    {
        public string SuccFulCode { get; set; }
        public string LineName { get; set; }
        public string DeptCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerAbbr { get; set; }
        public string DealerCode { get; set; }
        public string DealerAbbr { get; set; }
        public string DealerFullName { get; set; }
        public string LinkMan { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    }
}
