//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendFile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Contacts { get; set; }
        public string Address { get; set; }
        public string Emailcode { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Department { get; set; }
        public string DepartmentId { get; set; }
        public string Company { get; set; }
        public string CompanyId { get; set; }
    }
}
